config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'posts#index'

  resource :user, only: %i[] do
    get :login, to: 'user#login'
    get :logout, to: 'user#logout'
    post :accept, to: 'user#accept'
  end

  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[create]
    resource :like, only: %i[destroy create]
    resources :likes, only: %i[create destroy]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'exception_check' => 'monitor#exception_check', as: :rails_exception
  get 'sentry_check' => 'monitor#sentry_check', as: :sentry_exception

  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :post

  validates :name, presence: true, uniqueness: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include ActionView::Helpers::DateHelper
  belongs_to :category
  belongs_to :creator, class_name: 'User'

  validates :title, length: { minimum: 5, maximum: 255 }
  validates :body, length: { minimum: 200, maximum: 4000 }

  scope :latest, -> { order(created_at: :desc) }

  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :post_comments

  def time_interval
    distance_of_time_in_words(created_at, Time.current)
  end

  def comments
    post_comments.root_comments.order(created_at: :desc)
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_ancestry

  validates :content, length: { minimum: 5, maximum: 400 }

  scope :root_comments, -> { where(ancestry: '/') }
  scope :recent_comments, -> { order(created_at: :desc) }

  def comments
    children.recent_comments
  end
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'creator_id'
  has_many :comments, class_name: 'PostComment'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  add_flash_types :success
  rescue_from StandardError, with: :process_internal_server_error

  def render_unauthorized
    render file: 'public/401.html', status: :unauthorized
  end

  private

  def process_internal_server_error(exception)
    Rails.logger.error("Unhandled exception: #{exception.message}")
    Rails.logger.error(exception.backtrace.join("\n"))
    capture_to_sentry(exception)
    render file: Rails.public_path.join('500.html'),
           layout: false,
           status: :internal_server_error
  end

  def capture_to_sentry(exception)
    if Rails.application.config.enable_sentry
      Sentry.with_scope do |scope|
        scope.set_context(
          'params',
          params.to_unsafe_h
        )
        Sentry.capture_exception(exception)
      end
    end
    raise exception
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = current_post
    @parent = parent_comment

    @comment = current_user.comments.build(**params_permitted.to_hash, post: @post, parent: @parent)

    if @comment.save
      flash[:success] = t('messages.comment_created')
    else
      flash[:alert] = @comment.errors.full_messages.join('. ')
    end
    redirect_to post_path(@post)
  end

  private

  def params_permitted
    @params_permitted || @params_permitted = params.require(:post_comment).permit(:parent_id, :content)
  end

  def current_post
    Post.find(params[:post_id])
  end

  def parent_comment
    return if params_permitted[:parent_id].blank?

    PostComment.find(params_permitted[:parent_id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def set_post
    @post = Post.find(params.require(:post_id))
  end

  def create
    @post.likes.create(post: @post, user: current_user)
    redirect_to post_path(@post)
  end

  def destroy
    @post.likes.find_by(user: current_user)&.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/monitor_controller.rb
# frozen_string_literal: true

class MonitorController < ApplicationController
  def exception_check
    raise StandardError, 'Test exception'
  end

  def sentry_check
    if Rails.application.config.enable_sentry
      Sentry.capture_exception(Exception.new('Sentry test exception'))
    end
    redirect_to '/'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_current_post, only: %i[show]

  def index
    @posts = Post.latest.all
  end

  def show
    @new_comment = PostComment.new
  end

  def new
    return render_unauthorized unless user_signed_in?

    @post = Post.new
  end

  def create
    return render_unauthorized unless user_signed_in?

    @post = Post.new(post_params)
    @post.status = 'published'
    @post.creator = current_user
    if @post.save
      redirect_to posts_path(@post), success: t('messages.post_created')
    else
      flash[:alert] = t('messages.post_create_failed')
      render :new, status: :unprocessable_content, alert:
    end
  end

  def new_comment(parent)
    case parent
    when Post
      parent.comments.new
    when PostComment
      parent.children.new
    else
      raise Exception("Unknown parent type #{parent.class.name}. This can't happen")
    end
  end

  def liked_by_current_user?
    @post.likes.exists?(user: current_user)
  end

  def liked?
    @post.likes.exists?(user: current_user)
  end

  private

  def post_params
    params.require(:post).permit(%i[title body category_id])
  end

  def set_current_post
    @post = Post.find(params.require(:id))
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, alert: t('post.not_found')
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :html, :json

  def create
    super do |user|
      render json: { user: user.as_json(only: %i[id email]) } and return if request.format.json?

      redirect_to root_path and return
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_header.html.slim
.d-flex.flex-row.justify-content-between.align-items-center.border-bottom.mb-3
    = link_to root_path, class: 'h1' do
      i.bi.bi-signpost-split
    ul.nav.nav-pills
      li.text-muted
      - if current_user.nil?
        li.nav-item.me-2
          = link_to t('user.login'), new_user_session_path,
            class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('user.register'), new_user_registration_path,
            class: 'nav-link link-dark'
      - else
        p.m-2.text-muted
          = current_user&.email
        li.nav-item.me-2
          = link_to t('posts.create_post'), new_post_path,
            class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('user.logout'), destroy_user_session_path,
            class: 'nav-link link-dark'

app/views/layouts/_messages.html.slim
- if notice
  p.alert.alert-info
    = notice
- if success
  p.alert.alert-success
    = success
- if alert
  p.alert.alert-danger
    = alert

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || 'Rails Project 64'
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="apple-mobile-web-app-capable" content="yes"]
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link[rel="manifest" href="/manifest.json"]
    link[rel="icon" href="/icon.png" type="image/png"]
    link[rel="icon" href="/icon.svg" type="image/svg+xml"]
    link[rel="apple-touch-icon" href="/icon.png"]
    = stylesheet_link_tag 'application', "data-turbo-track": 'reload'
    = stylesheet_link_tag 'custom', media: 'all', data: { turbolinks: false }
    = javascript_include_tag 'application', "data-turbo-track": 'reload',
      type: 'module'
  body
    .container.d-flex.flex-column
      = render '/layouts/header'
      = render '/layouts/messages'
      = yield

app/views/posts/_comment_chain_view.html.slim
- new_comment = controller.new_comment(parent)
.container
  - unless parent.is_a? Post
    .container id="collapse-target-#{parent.id}" class="collapse"
      = render 'comment_form', comment: new_comment, post: @post
  - parent.comments.each do |c|
    - unless c.new_record?
      .card.rounded-0.m-1
        .card-header.d-flex.flex-row.align-items-center
          span.me-3
            = link_to '#', post_path(post)
          span.me-3
            = c.user.email
          span.me-3.text-muted.fs-6
            = l(c.created_at, format: '%e %B, %k:%M')
        .card-body
          p.card-text.break-words
            = sanitize(c.content)
        - if controller.user_signed_in?
          .card-footer
            = link_to t('post_comment.reply'), '#',
                class: 'text-decoration-underline text-lowercase',
                type: 'button',
                data: { bs_toggle: 'collapse',
                    bs_target: "#collapse-target-#{c.id}" },
                aria: { expanded: 'false',
                    controls: "collapse-target-#{c.id}" }
        .m-1.mb-2
          = render 'comment_chain_view', post: post, parent: c

app/views/posts/_comment_form.html.slim
.container.my-0.p-2
  = simple_form_for comment, url: post_comments_path(post) do |f|
    = f.hidden_field :parent_id, value: comment.parent&.id
    = f.input :content, label: false
    = f.submit class: 'btn btn-primary',
        value: t('post_comment.create')

app/views/posts/_post_card.html.slim
.container.border.rounded
  .d-flex.flex-column.p-2
    h2.h5
      =link_to sanitize(post.title), post_path(post),
        class: 'link-dark text-decoration-none'
    p.break-words
      = simple_format(post.body, {}, wrapper_tag: 'span', sanitize: true)
    .d-flex.flex-row.align-items-center
      .d-flex.flex-row.align-items-center.me-5
        .p.small.text-muted.me-1
          = t('post.liked')
        .badge.rounded-pill.text-bg-secondary
          = post.likes.size
      .p.small.text-muted.me-5
        = post.time_interval
      .p.small.text-muted.me-5
        = post.creator&.email

app/views/posts/_post_form.html.slim
=simple_form_for(@post, url: posts_path,
        html: { data: { turbolinks: false } }) do |f|
    = f.input :title
    = f.input :body
    = f.association :category
    = f.submit class: 'btn btn-primary', value: t('post.create')

app/views/posts/_post_show.html.slim
container.d-flex.flex-column.m-0
  .container.p-0.my-2
    ol.breadcrumb
      li.breadcrumb-item = link_to t('posts.all_posts'), posts_path
      li.breadcrumb-item.active = post.category.name
  h1.mb-4.mb-lg-5.break-words
    = sanitize(post.title)
  p.break-words
    = simple_format(post.body, {}, wrapper_tag: 'span', sanitize: true)
  .d-flex.flex-row.justify-content-between.bg-light.border-top.border-bottom.m-0.p-2
    .d-flex.flex-row
      .p.me-5
        = post.creator&.email
      .p.me-5
        = post.time_interval
    .p.d-flex.flex-row
      .me-2
        = post.likes.size
      .m-0
        - if controller.liked?
            =link_to post_like_path(post), method: :post, data: { turbo_method: :delete }, class: 'link-dark' do
                i.bi class="bi-hand-thumbs-up-fill"
        - else
            =link_to post_like_path(post), method: :post, data: { turbo_method: :post }, class: 'link-dark' do
                i.bi class="bi-hand-thumbs-up"

app/views/posts/index.html.slim
== content_for :title do
  = t('posts.title')

h1 #{t('posts.title')}
.d-flex.flex-column
  - if @posts.empty?
    = p t('posts.empty')
  - else
    - @posts.each do |p|
      = render 'post_card', post: p

app/views/posts/new.html.slim
== content_for :title do
  = t('posts.create_post')
= render('post_form')

app/views/posts/show.html.slim
.container.m-0.p-0
  = render 'post_show', post: @post
  .container.m-0.p-0.lead
    p.ms-2.mb-0
      = t('post.comments_title')
    - if controller.user_signed_in?
      = render 'comment_form', post: @post,
          comment: controller.new_comment(@post)
    = render 'comment_chain_view', parent: @post, post: @post